apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s

  - name: TimescaleDB
    uid: timescaledb
    type: grafana-postgresql-datasource
    url: db:5432
    user: grafana_reader
    jsonData:
      database: ${PGDATABASE}
      sslmode: disable
      timescaledb: true
      postgresVersion: 1600
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
